# Generated by Django 5.0.6 on 2024-05-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='contact',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='tournaments.golfcourse'),
        ),
    ]
