# Generated by Django 4.2 on 2024-06-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitor',
            old_name='competitor',
            new_name='user_profile',
        ),
    ]
