# Generated by Django 5.0.6 on 2024-05-27 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_tournament_contact_alter_tournament_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tee_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
    ]
