# Generated by Django 5.0.6 on 2024-05-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournament_tee_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='course',
            field=models.ManyToManyField(blank=True, to='tournaments.golfcourse'),
        ),
    ]
