# Generated by Django 5.0.6 on 2024-05-29 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_tournament_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='hcp_relevant',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='course',
        ),
        migrations.AddField(
            model_name='tournament',
            name='course',
            field=models.ForeignKey(blank=True, default=9999999999999, on_delete=django.db.models.deletion.CASCADE, to='tournaments.golfcourse'),
            preserve_default=False,
        ),
    ]
