# Generated by Django 5.0.6 on 2024-05-29 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_comment_tournament_hcp_relevant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.golfcourse'),
        ),
    ]
