# Generated by Django 4.2 on 2024-06-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_golfcourse_id_alter_tournament_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
